### PR TITLE
Fix asciiart

### PR DESCRIPTION
**Pull request by haboutnnah**
I made this on mobile sorry for bad commit message

### CODE REVIEW

**Comment by haboutnnah** [comment]
Ah you already fixed it nvm

Anyway, recommend adding the spaces for eol

**Review by andreapaiola — CHANGES_REQUESTED** [review]
please update from master and review this PR

thanks :dancing_women:

**Comment by haboutnnah** [comment]
Im on mobile rn sorry, just see the diff and implement the changes, it's just some spaces added to the ends of lines :)

**Comment by andreapaiola** [comment]
ah ah ok no problem :)

**Comment by haboutnnah** [comment]
Consider implementing these changes on your mdl repo too, I would make a pull but even changing a text file on mobile is hard

**Comment by andreapaiola** [comment]
ok

**Pull request closed without merging**
