### PR TITLE
Make readme play nice with github

### PR DESCRIPTION
**Pull request by haboutnnah**

### CODE REVIEW

**Comment by andreapaiola** [comment]
thank you :+1:  but the ASCII ART IS GONE... well I'll fix it...

**Comment by haboutnnah** [comment]
Also for your ascii art, use GitHub markdown backticks (Google). To add a line break, add 2 spaces at the end of a line.

**Comment by haboutnnah** [comment]
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by andreapaiola** [comment]
I see... fixed :ok_hand:

**Pull request merged**
